In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score, make_scorer, log_loss, roc_auc_score
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

In [3]:
df = pd.read_csv("dataset/financial-fraud-detection-dataset/versions/1/Synthetic_Financial_datasets_log.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

In [5]:
df = df.drop(columns=['nameOrig', 'nameDest'])
df.head()

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,170136.0,160296.36,0.0,0.0,0,0
1,1,PAYMENT,1864.28,21249.0,19384.72,0.0,0.0,0,0
2,1,TRANSFER,181.00,181.0,0.00,0.0,0.0,1,0
3,1,CASH_OUT,181.00,181.0,0.00,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,41554.0,29885.86,0.0,0.0,0,0

In [6]:
X = df.drop(columns=['isFraud', 'isFlaggedFraud'])
y = df['isFraud']

X['is_CASH_IN'] = X['type'].map({'CASH_IN':1, 'PAYMENT':0, 'CASH_OUT':0, 'TRANSFER':0, 'DEBIT':0})
X['is_PAYMENT'] = X['type'].map({'CASH_IN':0, 'PAYMENT':1, 'CASH_OUT':0, 'TRANSFER':0, 'DEBIT':0})
X['is_CASH_OUT'] = X['type'].map({'CASH_IN':0, 'PAYMENT':0, 'CASH_OUT':1, 'TRANSFER':0, 'DEBIT':0})
X['is_TRANSFER'] = X['type'].map({'CASH_IN':0, 'PAYMENT':0, 'CASH_OUT':0, 'TRANSFER':1, 'DEBIT':0})
X['is_DEBIT'] = X['type'].map({'CASH_IN':0, 'PAYMENT':0, 'CASH_OUT':0, 'TRANSFER':0, 'DEBIT':1})

X = X.drop(columns=['type'])

X.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,is_CASH_IN,is_PAYMENT,is_CASH_OUT,is_TRANSFER,is_DEBIT
0,1,9839.64,170136.0,160296.36,0.0,0.0,0,1,0,0,0
1,1,1864.28,21249.0,19384.72,0.0,0.0,0,1,0,0,0
2,1,181.00,181.0,0.00,0.0,0.0,0,0,0,1,0
3,1,181.00,181.0,0.00,21182.0,0.0,0,0,1,0,0
4,1,11668.14,41554.0,29885.86,0.0,0.0,0,1,0,0,0

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=42)

In [8]:
logreg = LogisticRegression(class_weight='balanced',random_state=42)
logreg.fit(X_train, y_train)


y_pred = logreg.predict(X_test)
y_proba = logreg.predict_proba(X_test)[:,1]

accuracy = accuracy_score(y_test, y_pred)
print(f"Akurasi model Logistic Regression: {accuracy:.2f}")

Akurasi model Logistic Regression: 0.91

In [9]:
logloss_score = log_loss(y_test, y_proba)
print(f"Log loss: {logloss_score:.2f}")
roc_auc = roc_auc_score(y_test, y_proba)
print(f"ROC AUC Score: {roc_auc:.2f}")
y_train_pred = logreg.predict(X_train)
y_test_pred = logreg.predict(X_test)

recall_train = recall_score(y_train, y_train_pred)
recall_test = recall_score(y_test, y_test_pred)

print(f"Training Recall: {recall_train:.2f}")
print(f"Test Recall: {recall_test:.2f}\n")
print(classification_report(y_test, y_pred))

Log loss: 0.33
ROC AUC Score: 0.96
Training Recall: 0.90
Test Recall: 0.88

              precision    recall  f1-score   support

           0       1.00      0.91      0.95   1906351
           1       0.01      0.88      0.02      2435

    accuracy                           0.91   1908786
   macro avg       0.51      0.90      0.49   1908786
weighted avg       1.00      0.91      0.95   1908786

In [10]:
cat_clf = CatBoostClassifier()
rf_clf = RandomForestClassifier()
xgb_clf = XGBClassifier()

voting_clf = VotingClassifier(
    estimators=[('cat', cat_clf), ('rf', rf_clf), ('xgb', xgb_clf)],
    voting='soft'
)

voting_clf.fit(X_train, y_train)

Learning rate set to 0.372343
0:	learn: 0.0621733	total: 713ms	remaining: 11m 52s
1:	learn: 0.0165981	total: 1.27s	remaining: 10m 36s
2:	learn: 0.0102415	total: 1.76s	remaining: 9m 46s
3:	learn: 0.0050278	total: 2.34s	remaining: 9m 42s
4:	learn: 0.0035167	total: 2.87s	remaining: 9m 31s
5:	learn: 0.0026662	total: 3.37s	remaining: 9m 18s
6:	learn: 0.0024240	total: 3.89s	remaining: 9m 12s
7:	learn: 0.0022946	total: 4.45s	remaining: 9m 11s
8:	learn: 0.0022304	total: 4.95s	remaining: 9m 5s
9:	learn: 0.0021243	total: 5.49s	remaining: 9m 3s
10:	learn: 0.0019940	total: 5.99s	remaining: 8m 58s
11:	learn: 0.0019374	total: 6.54s	remaining: 8m 58s
12:	learn: 0.0018850	total: 7.05s	remaining: 8m 55s
13:	learn: 0.0018112	total: 7.55s	remaining: 8m 52s
14:	learn: 0.0017625	total: 8.05s	remaining: 8m 48s
15:	learn: 0.0017337	total: 8.59s	remaining: 8m 48s
16:	learn: 0.0017194	total: 9.1s	remaining: 8m 45s
17:	learn: 0.0016799	total: 9.62s	remaining: 8m 44s
18:	learn: 0.0016130	total: 10.1s	remaining: 8m 42s
19:	learn: 0.0016020	total: 10.6s	remaining: 8m 40s
20:	learn: 0.0015872	total: 11.1s	remaining: 8m 38s
21:	learn: 0.0015567	total: 11.6s	remaining: 8m 37s
22:	learn: 0.0015484	total: 12.2s	remaining: 8m 36s
23:	learn: 0.0015417	total: 12.7s	remaining: 8m 36s
24:	learn: 0.0015112	total: 13.3s	remaining: 8m 37s
25:	learn: 0.0015015	total: 13.8s	remaining: 8m 36s
26:	learn: 0.0014922	total: 14.3s	remaining: 8m 35s
27:	learn: 0.0014545	total: 14.9s	remaining: 8m 35s
28:	learn: 0.0014437	total: 15.3s	remaining: 8m 33s
29:	learn: 0.0014130	total: 15.9s	remaining: 8m 33s
30:	learn: 0.0013903	total: 16.4s	remaining: 8m 32s
31:	learn: 0.0013732	total: 16.9s	remaining: 8m 31s
32:	learn: 0.0013667	total: 17.4s	remaining: 8m 30s
33:	learn: 0.0013479	total: 17.9s	remaining: 8m 28s
34:	learn: 0.0013304	total: 18.4s	remaining: 8m 27s
35:	learn: 0.0013172	total: 19s	remaining: 8m 28s
36:	learn: 0.0013123	total: 19.5s	remaining: 8m 26s
37:	learn: 0.0013044	total: 19.9s	remaining: 8m 24s
38:	learn: 0.0012984	total: 20.5s	remaining: 8m 25s
39:	learn: 0.0012907	total: 21s	remaining: 8m 24s
40:	learn: 0.0012839	total: 21.5s	remaining: 8m 23s
41:	learn: 0.0012772	total: 22.1s	remaining: 8m 23s
42:	learn: 0.0012752	total: 22.5s	remaining: 8m 21s
43:	learn: 0.0012594	total: 23s	remaining: 8m 20s
44:	learn: 0.0012412	total: 23.5s	remaining: 8m 19s
45:	learn: 0.0012295	total: 24s	remaining: 8m 18s
46:	learn: 0.0011703	total: 24.5s	remaining: 8m 17s
47:	learn: 0.0011676	total: 25s	remaining: 8m 16s
48:	learn: 0.0011209	total: 25.6s	remaining: 8m 16s
49:	learn: 0.0010781	total: 26.1s	remaining: 8m 15s
50:	learn: 0.0010525	total: 26.6s	remaining: 8m 14s
51:	learn: 0.0010454	total: 27.1s	remaining: 8m 13s
52:	learn: 0.0010396	total: 27.6s	remaining: 8m 12s
53:	learn: 0.0010191	total: 28.1s	remaining: 8m 11s
54:	learn: 0.0010064	total: 28.6s	remaining: 8m 10s
55:	learn: 0.0009961	total: 29.1s	remaining: 8m 10s
56:	learn: 0.0009929	total: 29.6s	remaining: 8m 9s
57:	learn: 0.0009891	total: 30.1s	remaining: 8m 8s
58:	learn: 0.0009737	total: 30.6s	remaining: 8m 8s
59:	learn: 0.0009667	total: 31.2s	remaining: 8m 8s
60:	learn: 0.0009597	total: 31.6s	remaining: 8m 7s
61:	learn: 0.0009581	total: 32.1s	remaining: 8m 5s
62:	learn: 0.0009525	total: 32.6s	remaining: 8m 5s
63:	learn: 0.0009358	total: 33.1s	remaining: 8m 4s
64:	learn: 0.0009316	total: 33.6s	remaining: 8m 3s
65:	learn: 0.0009229	total: 34.1s	remaining: 8m 3s
66:	learn: 0.0009215	total: 34.6s	remaining: 8m 2s
67:	learn: 0.0009185	total: 35.1s	remaining: 8m 1s
68:	learn: 0.0009152	total: 35.6s	remaining: 8m
69:	learn: 0.0009084	total: 36.1s	remaining: 7m 59s
70:	learn: 0.0009078	total: 36.6s	remaining: 7m 58s
71:	learn: 0.0008990	total: 37.1s	remaining: 7m 58s
72:	learn: 0.0008945	total: 37.7s	remaining: 7m 58s
73:	learn: 0.0008938	total: 38.3s	remaining: 7m 58s
74:	learn: 0.0008859	total: 38.8s	remaining: 7m 57s
75:	learn: 0.0008744	total: 39.3s	remaining: 7m 57s
76:	learn: 0.0008692	total: 39.8s	remaining: 7m 56s
77:	learn: 0.0008652	total: 40.3s	remaining: 7m 56s
78:	learn: 0.0008644	total: 40.8s	remaining: 7m 55s
79:	learn: 0.0008593	total: 41.3s	remaining: 7m 55s
80:	learn: 0.0008581	total: 41.9s	remaining: 7m 55s
81:	learn: 0.0008544	total: 42.4s	remaining: 7m 54s
82:	learn: 0.0008475	total: 42.9s	remaining: 7m 53s
83:	learn: 0.0008426	total: 43.4s	remaining: 7m 53s
84:	learn: 0.0008403	total: 43.9s	remaining: 7m 52s
85:	learn: 0.0008331	total: 44.4s	remaining: 7m 52s
86:	learn: 0.0008280	total: 45s	remaining: 7m 51s
87:	learn: 0.0008219	total: 45.5s	remaining: 7m 51s
88:	learn: 0.0008177	total: 46s	remaining: 7m 50s
89:	learn: 0.0008167	total: 46.5s	remaining: 7m 49s
90:	learn: 0.0008083	total: 47s	remaining: 7m 49s
91:	learn: 0.0008002	total: 47.5s	remaining: 7m 48s
92:	learn: 0.0007972	total: 48s	remaining: 7m 47s
93:	learn: 0.0007948	total: 48.5s	remaining: 7m 47s
94:	learn: 0.0007915	total: 49s	remaining: 7m 47s
95:	learn: 0.0007903	total: 49.5s	remaining: 7m 46s
96:	learn: 0.0007855	total: 50s	remaining: 7m 45s
97:	learn: 0.0007841	total: 50.5s	remaining: 7m 44s
98:	learn: 0.0007788	total: 51s	remaining: 7m 44s
99:	learn: 0.0007740	total: 51.5s	remaining: 7m 43s
100:	learn: 0.0007726	total: 52s	remaining: 7m 43s
101:	learn: 0.0007711	total: 52.5s	remaining: 7m 42s
102:	learn: 0.0007660	total: 53s	remaining: 7m 41s
103:	learn: 0.0007638	total: 53.6s	remaining: 7m 41s
104:	learn: 0.0007628	total: 54.1s	remaining: 7m 40s
105:	learn: 0.0007603	total: 54.6s	remaining: 7m 40s
106:	learn: 0.0007595	total: 55.1s	remaining: 7m 39s
107:	learn: 0.0007581	total: 55.6s	remaining: 7m 38s
108:	learn: 0.0007549	total: 56.1s	remaining: 7m 38s
109:	learn: 0.0007535	total: 56.7s	remaining: 7m 38s
110:	learn: 0.0007500	total: 57.2s	remaining: 7m 38s
111:	learn: 0.0007476	total: 57.7s	remaining: 7m 37s
112:	learn: 0.0007462	total: 58.1s	remaining: 7m 36s
113:	learn: 0.0007426	total: 58.6s	remaining: 7m 35s
114:	learn: 0.0007407	total: 59.1s	remaining: 7m 35s
115:	learn: 0.0007387	total: 59.6s	remaining: 7m 34s
116:	learn: 0.0007371	total: 1m	remaining: 7m 33s
117:	learn: 0.0007328	total: 1m	remaining: 7m 33s
118:	learn: 0.0007324	total: 1m 1s	remaining: 7m 32s
119:	learn: 0.0007287	total: 1m 1s	remaining: 7m 31s
120:	learn: 0.0007250	total: 1m 2s	remaining: 7m 31s
121:	learn: 0.0007240	total: 1m 2s	remaining: 7m 31s
122:	learn: 0.0007232	total: 1m 3s	remaining: 7m 30s
123:	learn: 0.0007192	total: 1m 3s	remaining: 7m 29s
124:	learn: 0.0007157	total: 1m 4s	remaining: 7m 29s
125:	learn: 0.0007113	total: 1m 4s	remaining: 7m 28s
126:	learn: 0.0007068	total: 1m 5s	remaining: 7m 28s
127:	learn: 0.0007044	total: 1m 5s	remaining: 7m 27s
128:	learn: 0.0006992	total: 1m 6s	remaining: 7m 27s
129:	learn: 0.0006985	total: 1m 6s	remaining: 7m 26s
130:	learn: 0.0006950	total: 1m 7s	remaining: 7m 26s
131:	learn: 0.0006904	total: 1m 7s	remaining: 7m 26s
132:	learn: 0.0006875	total: 1m 8s	remaining: 7m 25s
133:	learn: 0.0006848	total: 1m 8s	remaining: 7m 24s
134:	learn: 0.0006840	total: 1m 9s	remaining: 7m 24s
135:	learn: 0.0006820	total: 1m 9s	remaining: 7m 23s
136:	learn: 0.0006792	total: 1m 10s	remaining: 7m 23s
137:	learn: 0.0006786	total: 1m 10s	remaining: 7m 22s
138:	learn: 0.0006761	total: 1m 11s	remaining: 7m 22s
139:	learn: 0.0006739	total: 1m 11s	remaining: 7m 21s
140:	learn: 0.0006727	total: 1m 12s	remaining: 7m 21s
141:	learn: 0.0006721	total: 1m 12s	remaining: 7m 20s
142:	learn: 0.0006688	total: 1m 13s	remaining: 7m 20s
143:	learn: 0.0006668	total: 1m 13s	remaining: 7m 19s
144:	learn: 0.0006663	total: 1m 14s	remaining: 7m 18s
145:	learn: 0.0006644	total: 1m 14s	remaining: 7m 18s
146:	learn: 0.0006632	total: 1m 15s	remaining: 7m 17s
147:	learn: 0.0006621	total: 1m 15s	remaining: 7m 17s
148:	learn: 0.0006596	total: 1m 16s	remaining: 7m 17s
149:	learn: 0.0006585	total: 1m 17s	remaining: 7m 16s
150:	learn: 0.0006575	total: 1m 17s	remaining: 7m 15s
151:	learn: 0.0006534	total: 1m 18s	remaining: 7m 15s
152:	learn: 0.0006526	total: 1m 18s	remaining: 7m 14s
153:	learn: 0.0006482	total: 1m 19s	remaining: 7m 14s
154:	learn: 0.0006466	total: 1m 19s	remaining: 7m 13s
155:	learn: 0.0006450	total: 1m 20s	remaining: 7m 13s
156:	learn: 0.0006425	total: 1m 20s	remaining: 7m 12s
157:	learn: 0.0006402	total: 1m 21s	remaining: 7m 12s
158:	learn: 0.0006386	total: 1m 21s	remaining: 7m 11s
159:	learn: 0.0006375	total: 1m 22s	remaining: 7m 11s
160:	learn: 0.0006355	total: 1m 22s	remaining: 7m 10s
161:	learn: 0.0006324	total: 1m 23s	remaining: 7m 9s
162:	learn: 0.0006305	total: 1m 23s	remaining: 7m 9s
163:	learn: 0.0006277	total: 1m 24s	remaining: 7m 8s
164:	learn: 0.0006241	total: 1m 24s	remaining: 7m 8s
165:	learn: 0.0006212	total: 1m 25s	remaining: 7m 8s
166:	learn: 0.0006193	total: 1m 25s	remaining: 7m 7s
167:	learn: 0.0006183	total: 1m 26s	remaining: 7m 7s
168:	learn: 0.0006133	total: 1m 26s	remaining: 7m 6s
169:	learn: 0.0006099	total: 1m 27s	remaining: 7m 6s
170:	learn: 0.0006095	total: 1m 27s	remaining: 7m 5s
171:	learn: 0.0006089	total: 1m 28s	remaining: 7m 5s
172:	learn: 0.0006082	total: 1m 28s	remaining: 7m 4s
173:	learn: 0.0006071	total: 1m 29s	remaining: 7m 4s
174:	learn: 0.0006055	total: 1m 29s	remaining: 7m 3s
175:	learn: 0.0006040	total: 1m 30s	remaining: 7m 3s
176:	learn: 0.0006023	total: 1m 30s	remaining: 7m 2s
177:	learn: 0.0006008	total: 1m 31s	remaining: 7m 2s
178:	learn: 0.0005995	total: 1m 31s	remaining: 7m 1s
179:	learn: 0.0005989	total: 1m 32s	remaining: 7m 1s
180:	learn: 0.0005985	total: 1m 32s	remaining: 7m
181:	learn: 0.0005968	total: 1m 33s	remaining: 7m
182:	learn: 0.0005961	total: 1m 33s	remaining: 6m 59s
183:	learn: 0.0005951	total: 1m 34s	remaining: 6m 58s
184:	learn: 0.0005946	total: 1m 34s	remaining: 6m 57s
185:	learn: 0.0005934	total: 1m 35s	remaining: 6m 57s
186:	learn: 0.0005928	total: 1m 35s	remaining: 6m 56s
187:	learn: 0.0005902	total: 1m 36s	remaining: 6m 56s
188:	learn: 0.0005884	total: 1m 36s	remaining: 6m 55s
189:	learn: 0.0005865	total: 1m 37s	remaining: 6m 55s
190:	learn: 0.0005863	total: 1m 37s	remaining: 6m 54s
191:	learn: 0.0005846	total: 1m 38s	remaining: 6m 53s
192:	learn: 0.0005822	total: 1m 38s	remaining: 6m 53s
193:	learn: 0.0005808	total: 1m 39s	remaining: 6m 53s
194:	learn: 0.0005791	total: 1m 39s	remaining: 6m 52s
195:	learn: 0.0005772	total: 1m 40s	remaining: 6m 51s
196:	learn: 0.0005747	total: 1m 40s	remaining: 6m 51s
197:	learn: 0.0005715	total: 1m 41s	remaining: 6m 50s
198:	learn: 0.0005703	total: 1m 41s	remaining: 6m 50s
199:	learn: 0.0005700	total: 1m 42s	remaining: 6m 49s
200:	learn: 0.0005683	total: 1m 42s	remaining: 6m 49s
201:	learn: 0.0005664	total: 1m 43s	remaining: 6m 48s
202:	learn: 0.0005658	total: 1m 44s	remaining: 6m 48s
203:	learn: 0.0005642	total: 1m 44s	remaining: 6m 48s
204:	learn: 0.0005631	total: 1m 45s	remaining: 6m 47s
205:	learn: 0.0005619	total: 1m 45s	remaining: 6m 47s
206:	learn: 0.0005605	total: 1m 46s	remaining: 6m 46s
207:	learn: 0.0005592	total: 1m 46s	remaining: 6m 46s
208:	learn: 0.0005574	total: 1m 47s	remaining: 6m 45s
209:	learn: 0.0005562	total: 1m 47s	remaining: 6m 45s
210:	learn: 0.0005558	total: 1m 48s	remaining: 6m 44s
211:	learn: 0.0005557	total: 1m 48s	remaining: 6m 44s
212:	learn: 0.0005536	total: 1m 49s	remaining: 6m 43s
213:	learn: 0.0005523	total: 1m 49s	remaining: 6m 43s
214:	learn: 0.0005507	total: 1m 50s	remaining: 6m 42s
215:	learn: 0.0005504	total: 1m 50s	remaining: 6m 42s
216:	learn: 0.0005479	total: 1m 51s	remaining: 6m 41s
217:	learn: 0.0005466	total: 1m 51s	remaining: 6m 41s
218:	learn: 0.0005455	total: 1m 52s	remaining: 6m 40s
219:	learn: 0.0005448	total: 1m 52s	remaining: 6m 40s
220:	learn: 0.0005424	total: 1m 53s	remaining: 6m 39s
221:	learn: 0.0005420	total: 1m 53s	remaining: 6m 38s
222:	learn: 0.0005396	total: 1m 54s	remaining: 6m 38s
223:	learn: 0.0005392	total: 1m 54s	remaining: 6m 37s
224:	learn: 0.0005378	total: 1m 55s	remaining: 6m 37s
225:	learn: 0.0005369	total: 1m 55s	remaining: 6m 36s
226:	learn: 0.0005356	total: 1m 56s	remaining: 6m 36s
227:	learn: 0.0005347	total: 1m 56s	remaining: 6m 35s
228:	learn: 0.0005345	total: 1m 57s	remaining: 6m 34s
229:	learn: 0.0005336	total: 1m 57s	remaining: 6m 34s
230:	learn: 0.0005320	total: 1m 58s	remaining: 6m 34s
231:	learn: 0.0005308	total: 1m 58s	remaining: 6m 33s
232:	learn: 0.0005299	total: 1m 59s	remaining: 6m 33s
233:	learn: 0.0005289	total: 1m 59s	remaining: 6m 32s
234:	learn: 0.0005265	total: 2m	remaining: 6m 32s
235:	learn: 0.0005253	total: 2m 1s	remaining: 6m 31s
236:	learn: 0.0005243	total: 2m 1s	remaining: 6m 31s
237:	learn: 0.0005238	total: 2m 2s	remaining: 6m 31s
238:	learn: 0.0005230	total: 2m 2s	remaining: 6m 30s
239:	learn: 0.0005227	total: 2m 3s	remaining: 6m 30s
240:	learn: 0.0005218	total: 2m 3s	remaining: 6m 29s
241:	learn: 0.0005208	total: 2m 4s	remaining: 6m 28s
242:	learn: 0.0005197	total: 2m 4s	remaining: 6m 28s
243:	learn: 0.0005189	total: 2m 5s	remaining: 6m 28s
244:	learn: 0.0005160	total: 2m 5s	remaining: 6m 27s
245:	learn: 0.0005149	total: 2m 6s	remaining: 6m 27s
246:	learn: 0.0005134	total: 2m 6s	remaining: 6m 26s
247:	learn: 0.0005129	total: 2m 7s	remaining: 6m 25s
248:	learn: 0.0005119	total: 2m 7s	remaining: 6m 25s
249:	learn: 0.0005114	total: 2m 8s	remaining: 6m 25s
250:	learn: 0.0005106	total: 2m 8s	remaining: 6m 24s
251:	learn: 0.0005093	total: 2m 9s	remaining: 6m 24s
252:	learn: 0.0005080	total: 2m 10s	remaining: 6m 24s
253:	learn: 0.0005066	total: 2m 11s	remaining: 6m 24s
254:	learn: 0.0005056	total: 2m 11s	remaining: 6m 24s
255:	learn: 0.0005049	total: 2m 12s	remaining: 6m 24s
256:	learn: 0.0005041	total: 2m 12s	remaining: 6m 23s
257:	learn: 0.0005039	total: 2m 13s	remaining: 6m 22s
258:	learn: 0.0005026	total: 2m 13s	remaining: 6m 22s
259:	learn: 0.0005017	total: 2m 14s	remaining: 6m 21s
260:	learn: 0.0005015	total: 2m 14s	remaining: 6m 21s
261:	learn: 0.0005008	total: 2m 15s	remaining: 6m 20s
262:	learn: 0.0004993	total: 2m 15s	remaining: 6m 19s
263:	learn: 0.0004989	total: 2m 16s	remaining: 6m 19s
264:	learn: 0.0004970	total: 2m 16s	remaining: 6m 18s
265:	learn: 0.0004969	total: 2m 17s	remaining: 6m 18s
266:	learn: 0.0004964	total: 2m 17s	remaining: 6m 17s
267:	learn: 0.0004948	total: 2m 18s	remaining: 6m 17s
268:	learn: 0.0004941	total: 2m 18s	remaining: 6m 16s
269:	learn: 0.0004934	total: 2m 19s	remaining: 6m 16s
270:	learn: 0.0004927	total: 2m 19s	remaining: 6m 15s
271:	learn: 0.0004917	total: 2m 20s	remaining: 6m 15s
272:	learn: 0.0004885	total: 2m 20s	remaining: 6m 14s
273:	learn: 0.0004871	total: 2m 21s	remaining: 6m 13s
274:	learn: 0.0004848	total: 2m 21s	remaining: 6m 12s
275:	learn: 0.0004842	total: 2m 21s	remaining: 6m 12s
276:	learn: 0.0004835	total: 2m 22s	remaining: 6m 11s
277:	learn: 0.0004834	total: 2m 22s	remaining: 6m 10s
278:	learn: 0.0004812	total: 2m 23s	remaining: 6m 10s
279:	learn: 0.0004807	total: 2m 23s	remaining: 6m 9s
280:	learn: 0.0004805	total: 2m 24s	remaining: 6m 8s
281:	learn: 0.0004788	total: 2m 24s	remaining: 6m 8s
282:	learn: 0.0004777	total: 2m 25s	remaining: 6m 7s
283:	learn: 0.0004765	total: 2m 25s	remaining: 6m 7s
284:	learn: 0.0004760	total: 2m 26s	remaining: 6m 6s
285:	learn: 0.0004747	total: 2m 26s	remaining: 6m 6s
286:	learn: 0.0004743	total: 2m 27s	remaining: 6m 5s
287:	learn: 0.0004737	total: 2m 27s	remaining: 6m 4s
288:	learn: 0.0004735	total: 2m 27s	remaining: 6m 3s
289:	learn: 0.0004730	total: 2m 28s	remaining: 6m 3s
290:	learn: 0.0004727	total: 2m 28s	remaining: 6m 2s
291:	learn: 0.0004722	total: 2m 29s	remaining: 6m 2s
292:	learn: 0.0004720	total: 2m 29s	remaining: 6m 1s
293:	learn: 0.0004714	total: 2m 30s	remaining: 6m
294:	learn: 0.0004706	total: 2m 30s	remaining: 6m
295:	learn: 0.0004705	total: 2m 31s	remaining: 6m
296:	learn: 0.0004693	total: 2m 31s	remaining: 5m 59s
297:	learn: 0.0004683	total: 2m 32s	remaining: 5m 58s
298:	learn: 0.0004676	total: 2m 32s	remaining: 5m 58s
299:	learn: 0.0004662	total: 2m 33s	remaining: 5m 57s
300:	learn: 0.0004657	total: 2m 33s	remaining: 5m 57s
301:	learn: 0.0004643	total: 2m 34s	remaining: 5m 56s
302:	learn: 0.0004633	total: 2m 34s	remaining: 5m 56s
303:	learn: 0.0004625	total: 2m 35s	remaining: 5m 55s
304:	learn: 0.0004605	total: 2m 35s	remaining: 5m 54s
305:	learn: 0.0004597	total: 2m 36s	remaining: 5m 54s
306:	learn: 0.0004593	total: 2m 36s	remaining: 5m 53s
307:	learn: 0.0004583	total: 2m 37s	remaining: 5m 53s
308:	learn: 0.0004576	total: 2m 37s	remaining: 5m 52s
309:	learn: 0.0004567	total: 2m 38s	remaining: 5m 52s
310:	learn: 0.0004558	total: 2m 38s	remaining: 5m 51s
311:	learn: 0.0004550	total: 2m 39s	remaining: 5m 51s
312:	learn: 0.0004538	total: 2m 40s	remaining: 5m 51s
313:	learn: 0.0004528	total: 2m 40s	remaining: 5m 51s
314:	learn: 0.0004525	total: 2m 41s	remaining: 5m 50s
315:	learn: 0.0004514	total: 2m 41s	remaining: 5m 50s
316:	learn: 0.0004506	total: 2m 42s	remaining: 5m 50s
317:	learn: 0.0004496	total: 2m 43s	remaining: 5m 49s
318:	learn: 0.0004485	total: 2m 43s	remaining: 5m 49s
319:	learn: 0.0004484	total: 2m 44s	remaining: 5m 48s
320:	learn: 0.0004480	total: 2m 44s	remaining: 5m 48s
321:	learn: 0.0004471	total: 2m 45s	remaining: 5m 48s
322:	learn: 0.0004465	total: 2m 45s	remaining: 5m 47s
323:	learn: 0.0004457	total: 2m 46s	remaining: 5m 47s
324:	learn: 0.0004450	total: 2m 46s	remaining: 5m 46s
325:	learn: 0.0004446	total: 2m 47s	remaining: 5m 46s
326:	learn: 0.0004435	total: 2m 48s	remaining: 5m 45s
327:	learn: 0.0004431	total: 2m 48s	remaining: 5m 45s
328:	learn: 0.0004428	total: 2m 49s	remaining: 5m 44s
329:	learn: 0.0004417	total: 2m 49s	remaining: 5m 44s
330:	learn: 0.0004407	total: 2m 50s	remaining: 5m 44s
331:	learn: 0.0004400	total: 2m 50s	remaining: 5m 43s
332:	learn: 0.0004394	total: 2m 51s	remaining: 5m 43s
333:	learn: 0.0004385	total: 2m 51s	remaining: 5m 42s
334:	learn: 0.0004376	total: 2m 52s	remaining: 5m 42s
335:	learn: 0.0004370	total: 2m 53s	remaining: 5m 42s
336:	learn: 0.0004364	total: 2m 53s	remaining: 5m 41s
337:	learn: 0.0004361	total: 2m 54s	remaining: 5m 41s
338:	learn: 0.0004354	total: 2m 55s	remaining: 5m 41s
339:	learn: 0.0004351	total: 2m 55s	remaining: 5m 41s
340:	learn: 0.0004344	total: 2m 56s	remaining: 5m 40s
341:	learn: 0.0004337	total: 2m 57s	remaining: 5m 40s
342:	learn: 0.0004335	total: 2m 57s	remaining: 5m 40s
343:	learn: 0.0004328	total: 2m 58s	remaining: 5m 40s
344:	learn: 0.0004320	total: 2m 59s	remaining: 5m 41s
345:	learn: 0.0004311	total: 3m	remaining: 5m 41s
346:	learn: 0.0004297	total: 3m 1s	remaining: 5m 41s
347:	learn: 0.0004289	total: 3m 1s	remaining: 5m 40s
348:	learn: 0.0004279	total: 3m 2s	remaining: 5m 40s
349:	learn: 0.0004271	total: 3m 3s	remaining: 5m 39s
350:	learn: 0.0004269	total: 3m 3s	remaining: 5m 39s
351:	learn: 0.0004262	total: 3m 4s	remaining: 5m 39s
352:	learn: 0.0004251	total: 3m 5s	remaining: 5m 39s
353:	learn: 0.0004246	total: 3m 5s	remaining: 5m 38s
354:	learn: 0.0004242	total: 3m 6s	remaining: 5m 38s
355:	learn: 0.0004238	total: 3m 6s	remaining: 5m 37s
356:	learn: 0.0004234	total: 3m 7s	remaining: 5m 37s
357:	learn: 0.0004225	total: 3m 7s	remaining: 5m 36s
358:	learn: 0.0004223	total: 3m 8s	remaining: 5m 36s
359:	learn: 0.0004216	total: 3m 8s	remaining: 5m 35s
360:	learn: 0.0004213	total: 3m 9s	remaining: 5m 35s
361:	learn: 0.0004211	total: 3m 9s	remaining: 5m 34s
362:	learn: 0.0004200	total: 3m 10s	remaining: 5m 34s
363:	learn: 0.0004194	total: 3m 11s	remaining: 5m 33s
364:	learn: 0.0004188	total: 3m 11s	remaining: 5m 33s
365:	learn: 0.0004182	total: 3m 12s	remaining: 5m 32s
366:	learn: 0.0004171	total: 3m 12s	remaining: 5m 32s
367:	learn: 0.0004160	total: 3m 13s	remaining: 5m 32s
368:	learn: 0.0004157	total: 3m 14s	remaining: 5m 32s
369:	learn: 0.0004156	total: 3m 14s	remaining: 5m 31s
370:	learn: 0.0004146	total: 3m 15s	remaining: 5m 31s
371:	learn: 0.0004137	total: 3m 15s	remaining: 5m 30s
372:	learn: 0.0004128	total: 3m 16s	remaining: 5m 30s
373:	learn: 0.0004117	total: 3m 17s	remaining: 5m 29s
374:	learn: 0.0004112	total: 3m 17s	remaining: 5m 29s
375:	learn: 0.0004105	total: 3m 18s	remaining: 5m 29s
376:	learn: 0.0004103	total: 3m 18s	remaining: 5m 28s

VotingClassifier(estimators=[('cat',
                              <catboost.core.CatBoostClassifier object at 0x0000024D0B564E90>),
                             ('rf', RandomForestClassifier()),
                             ('xgb',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric=None,
                                            feature...
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=None, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=None,
                                            max_leaves=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=None, n_jobs=None,
                                            num_parallel_tree=None,
                                            random_state=None, ...))],
                 voting='soft')

In [11]:
labels = ['Negatif (0)', 'Positif (1)']

In [12]:
def evaluate_model(classifier, X_train, y_train, X_test, y_test):
    y_train_pred = classifier.predict(X_train)
    y_test_pred = classifier.predict(X_test)
    # on training
    recall_train = recall_score(y_train, y_train_pred)
    # on testing dataset
    recall_test = recall_score(y_test, y_test_pred)

    print(f'Training Recall: {recall_train:.3f}')
    print(f'Test Recall: {recall_test:.3f}')
    print("\nClassification Report (Test):")
    print(classification_report(y_test, y_test_pred))

    cm = confusion_matrix(y_test, y_test_pred)
    
    plt.figure(figsize=(6, 5))
    sns.heatmap(
        cm, 
        annot=True,        
        fmt='d',           
        cmap='Oranges',      
        xticklabels=labels,
        yticklabels=labels
    )
    plt.xlabel('Nilai Prediksi')
    plt.ylabel('Nilai Aktual')
    plt.title(f'Confusion Matrix Heatmap Voting Classifier')
    plt.show()

    return recall_train, recall_test

In [13]:
evaluate_model(voting_clf, X_train, y_train, X_test, y_test)

Training Recall: 0.952
Test Recall: 0.847

Classification Report (Test):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906351
           1       0.98      0.85      0.91      2435

    accuracy                           1.00   1908786
   macro avg       0.99      0.92      0.95   1908786
weighted avg       1.00      1.00      1.00   1908786

NameError: name 'sns' is not defined

In [ ]:
import joblib

# Save the trained model
joblib.dump(voting_clf, 'voting_classifier_model.pkl')
print("Model saved as 'voting_classifier_model.pkl'")